id: git_sync
namespace: my.project

triggers:
  - id: poll_github_every_minute
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "* * * * *" # This means every minute. Change to "*/5 * * * *" for every 5 minutes.

tasks:
  - id: sync
    type: io.kestra.plugin.git.Sync
    url: https://github.com/amrlasyraf/AWS-Project.git
    branch: main
    password: "{{ vars.github_token }}"