id: github_sync
namespace: ewallet.layer
tasks:
  - id: sync_repository
    type: io.kestra.plugin.git.SyncNamespaceFiles
    url: https://github.com/amrlasyraf/AWS-Project.git
    branch: main
    username: amrlasyraf
    password: "{{ secret('GITHUB_TOKEN') }}"
    namespace: ewallet.layer
    gitDirectory: kestra/
variables:
  sns_topic_arn: "arn:aws:sns:ap-southeast-1:400953388228:Kestra_Alerts"

triggers:
  - id: auto_sync
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "*/2 * * * *"